sw=0
numero=2
contador=1
incre=3
while(contador<=6):
    if(sw==0):
        print(numero)
flkshgkshgkjhksljbnknbmkhgiaehrgjkhskjlghkñlkmngfoijkñljbnafcpokqanñihyamiohkrb896877q32roafdiutasfkljgfv
        sw=0
    numero=numero+incre
    contador=contador+1