numero=1
incre=2
contador=1
sw=0
while(contador<=6):
    if(sw==0):
        print(numero)
        sw=1
    else:
        print(-numero)
        sw=0
    numero=numero+incre
    incre=incre*2
    contador=contador+1